spring.application.name=demo
server.port=18080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/exampledb
spring.datasource.username=exampleuser
spring.datasource.password=examplepass
